title: Jonathan Lynn
logo: /assets/img/logo.png
description: My name is Jonathan and I’m the proud owner of this fine website. The goal of this blog is to document and share my learnings as an ICT Network & Security Professional. You’ll find that the design is fairly minimal and straight forward designed to be accessible by all.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
